### ISSUE TITLE
Request for bash script

### ISSUE THREAD

**Issue by sswingHUA** [aviclu/peekacross#1]
Hi! Thanks for your great work, it means a lot for me. 
I would appreciate if you could kindly provide information about the parameters you used？

**Comment by aviclu** [comment]
As written in the instructions, check out the following repo for all the code and data regarding multi_news:
https://github.com/primer

**Comment by sswingHUA** [comment]
Sorry, I was editing the message when you responded to me. What I'd like to inquire about is whether you could kindly share information regarding the parameters you used?
